const constants = {
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_PENDING: "FETCH_CATEGORIES_PENDING",
  FETCH_CATEGORIES_ERROR: "FETCH_CATEGORIES_ERROR",
  FETCH_QUOTE_PENDING: "FETCH_QUOTE_PENDING",
  FETCH_QUOTE_SUCCESS: "FETCH_QUOTE_SUCCESS",
  FETCH_QUOTE_ERROR: "FETCH_QUOTE_ERROR",
  FETCH_RANDOMQUOTE_PENDING: "FETCH_RANDOMQUOTE_PENDING",
  FETCH_RANDOMQUOTE_SUCCESS: "FETCH_RANDOMQUOTE_SUCCESS",
  FETCH_RANDOMQUOTE_ERROR: "FETCH_RANDOMQUOTE_ERROR",
  FETCH_SEARCHQUOTE_PENDING: "FETCH_SEARCHQUOTE_PENDING",
  FETCH_SEARCHQUOTE_SUCCESS: "FETCH_SEARCHQUOTE_SUCCESS",
  FETCH_SEARCHQUOTE_ERROR: "FETCH_SEARCHQUOTE_ERROR",
  ADD_ERROR: "ADD_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR"
}

export default constants