const constants = {
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_PENDING: "FETCH_CATEGORIES_PENDING",
  FETCH_CATEGORIES_ERROR: "FETCH_CATEGORIES_ERROR",
  FETCH_QUOTE_TYPE: "FETCH_QUOTE_TYPE",
  FETCH_QUOTE_PENDING: "FETCH_QUOTE_PENDING",
  FETCH_QUOTE_SUCCESS: "FETCH_QUOTE_SUCCESS",
  FETCH_QUOTE_ERROR: "FETCH_QUOTE_ERROR",
  ADD_ERROR: "ADD_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR"
}

export default constants